all: main.c SimpleTopDownAllocator.c OwnTopDownAllocator.c TopDownAllocator.c BottomUpAllocator.c topdownallocator_main.c genericLL.c topdownallocator.h LinkedListLib.h lib.h
	gcc -o alloc main.c SimpleTopDownAllocator.c OwnTopDownAllocator.c TopDownAllocator.c BottomUpAllocator.c topdownallocator_main.c genericLL.c 

clean:
	rm -rf alloc